### ISSUE TITLE
why you upload node_modules

### ISSUE THREAD

**Issue by LryBackinblack** [Fredxingxing/webpack-learn#1]
![image](https://user-images.githubusercontent.com/12715042/91630400-baeb3680-ea03-11ea-80b8-7922e5d26033.png)![image](https://user-images.githubusercontent.com/12715042/91630400-baeb3680-ea03-11ea-80b8-7922e5d26033.png)![image](https://user-images.githubusercontent.com/12715042/91630400-baeb3680-ea03-11ea-80b8-7922e5d26033.png)![image](https://user-images.githubusercontent.com/12715042/91630400-baeb3680-ea03-11ea-80b8-7922e5d26033.png)![image](https://user-images.githubusercontent.com/12715042/91630400-baeb3680-ea03-11ea-80b8-7922e5d26033.png)

**Comment by Fredxingxing** [comment]
live and learn bro
